default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: skello_development
  
test:
  <<: *default
  database: skello_test

production:
  url: <%= ENV['DATABASE_URL'] %>